### ISSUE TITLE
Refreshing content

### ISSUE THREAD

**Issue by Jefken** [add-ons/plugin.video.vrt.nu#947]
I'm using this plugin on 2 amlogic devices, Kodi 18.9 and 19, Corelec, since 18 of april the content is not refreshing anymore.

Best regards.

```

**Comment by mediaminister** [comment]
VRT NU has changed the search API and this breaks loading content in the add-on.
I'll investigate.

**Comment by NofanTasi** [comment]
@Jefken @mediaminister  : same here ... good luck with the fix and I am happy to devtest it.

**Comment by mediaminister** [comment]
Most of the menu listing problems should be fixed in v2.5.9: https://github.com/add-ons/plugin.video.vrt.nu/releases/tag/v2.5.9
However this VRT NU API change causes more problems with other functionality like 'Up Next', Favorites and resumepoints.
I currently have no time to fix these other problems. I'll look at this at a later time.
For now, the add-on should be functional to browse and watch all VRT NU content again.

**Comment by NofanTasi** [comment]
The refresh is fixed ! Thanks! The seasons get odd numerical names like 'Season 1640081116950' (Het-Journaal) but they seem ordered in time so that's OK for now.

**Comment by WimDeWinter01** [comment]
I'm using plugin v2.5.9 installed from zip on manjaro linux, kodi 19 and I still can't watch any vrtnu content. I had, before the update to v2.5.9 a "http 503 error" issue in v2.5.8 as in #949, and since that is a duplicate of this issue I think my issue is like this one, so I post here as a reply.

My error log:
```
2022-04-20 21:51:35.328 T:13303    INFO <general>: initializing python engine.
2022-04-20 21:51:35.484 T:13303   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'UnboundLocalError'>
                                                   Error Contents: local variable 'sort' referenced before assignment
                                                   Traceback (most recent call last):
                                                     File "/home/wim/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon_entry.py", line 14, in <module>
                                                       run(argv)
                                                     File "/home/wim/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon.py", line 362, in run
                                                       plugin.run(argv)
                                                     File "/home/wim/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                       self._dispatch(self.path)
                                                     File "/home/wim/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                       view_func(**kwargs)
                                                     File "/home/wim/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon.py", line 176, in categories
                                                       VRTPlayer().show_category_menu(category=category)
                                                     File "/home/wim/.kodi/addons/plugin.video.vrt.nu/resources/lib/vrtplayer.py", line 213, in show_category_menu
                                                       tvshow_items = self._apihelper.list_tvshows(category=category)
                                                     File "/home/wim/.kodi/addons/plugin.video.vrt.nu/resources/lib/apihelper.py", line 84, in list_tvshows
                                                       return self.__map_tvshows(tvshows, oneoffs, use_favorites=use_favorites, cache_file=cache_file)
                                                     File "/home/wim/.kodi/addons/plugin.video.vrt.nu/resources/lib/apihelper.py", line 237, in __map_tvshows
                                                       items.append(self.episode_to_listitem(oneoffs[index], program, cache_file, titletype='oneoff')[0])
                                                     File "/home/wim/.kodi/addons/plugin.video.vrt.nu/resources/lib/apihelper.py", line 247, in episode_to_listitem
                                                       label, sort, ascending = self._metadata.get_label(episode, titletype, return_sort=True)
                                                     File "/home/wim/.kodi/addons/plugin.video.vrt.nu/resources/lib/metadata.py", line 779, in get_label
                                                       return colour(label), sort, ascending
                                                   UnboundLocalError: local variable 'sort' referenced before assignment
                                                   -->End of Python script error report<--
                                                   
2022-04-20 21:51:35.505 T:13303    INFO <general>: Python interpreter stopped
2022-04-20 21:51:35.510 T:13311   ERROR <general>: Skipped 1 duplicate messages..
2022-04-20 21:51:35.510 T:13311   ERROR <general>: GetDirectory - Error getting plugin://plugin.video.vrt.nu/categories/human-interest
2022-04-20 21:51:35.532 T:1486    ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.vrt.nu/categories/human-interest) failed
2022-04-20 21:51:35.533 T:13313    INFO <general>: initializing python engine.
2022-04-20 21:51:35.635 T:13313    INFO <general>: CPythonInvoker(34, /home/wim/.kodi/addons/plugin.video.vrt.nu/resources/lib/addon_entry.py): script successfully run
```

**Comment by Jefken** [comment]
Many thanks, fantasic news!
